// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/jackc/pgtype"
)

type PaymentTransactions struct {
	ID                     int64        `json:"id"`
	CreatedAt              time.Time    `json:"created_at"`
	UpdatedAt              time.Time    `json:"updated_at"`
	TransactionRef         string       `json:"transaction_ref"`
	Status                 bool         `json:"status"`
	TransactionComplete    bool         `json:"transaction_complete"`
	Data                   pgtype.JSONB `json:"data"`
	Code                   string       `json:"code"`
	PaymentIntegrationType int32        `json:"payment_integration_type"`
	PaymentPurpose         int32        `json:"payment_purpose"`
	Amount                 float64      `json:"amount"`
	PaymentMode            int32        `json:"payment_mode"`
	Currency               string       `json:"currency"`
	PhoneNumber            string       `json:"phone_number"`
	Fts                    interface{}  `json:"fts"`
}

type SchemaMigrations struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type Users struct {
	ID           int64          `json:"id"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	UserName     string         `json:"user_name"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	ProfileImage sql.NullString `json:"profile_image"`
	PhoneNumber  string         `json:"phone_number"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	Fts          interface{}    `json:"fts"`
}
