[database]
server = "192.168.0.102"
port = "5432"
database = "ecobake"
user = "rvtn"
password = "rvtn"

[server]
address = "192.168.0.102"
port = "8090"

[minio]
user = "minioadmin"
password = "minioadmin"
server = "192.168.0.102"
port = "9000"
name = "rvtn"

