// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"ecobake/internal/models"
)

type LoginResp struct {
	User    *models.User `json:"user"`
	Refresh *string      `json:"refresh"`
	Access  *string      `json:"access"`
}

type LoginUser struct {
	Password string `json:"password"`
	Email    string `json:"email"`
}

type NewUser struct {
	Password    string `json:"password"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
}
