// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"ecobake/ent/favourites"
	"ecobake/ent/predicate"
	"ecobake/ent/product"
	"ecobake/ent/user"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FavouritesUpdate is the builder for updating Favourites entities.
type FavouritesUpdate struct {
	config
	hooks    []Hook
	mutation *FavouritesMutation
}

// Where appends a list predicates to the FavouritesUpdate builder.
func (fu *FavouritesUpdate) Where(ps ...predicate.Favourites) *FavouritesUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetCreatedAt sets the "created_at" field.
func (fu *FavouritesUpdate) SetCreatedAt(t time.Time) *FavouritesUpdate {
	fu.mutation.SetCreatedAt(t)
	return fu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fu *FavouritesUpdate) SetNillableCreatedAt(t *time.Time) *FavouritesUpdate {
	if t != nil {
		fu.SetCreatedAt(*t)
	}
	return fu
}

// SetUpdatedAt sets the "updated_at" field.
func (fu *FavouritesUpdate) SetUpdatedAt(t time.Time) *FavouritesUpdate {
	fu.mutation.SetUpdatedAt(t)
	return fu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fu *FavouritesUpdate) SetNillableUpdatedAt(t *time.Time) *FavouritesUpdate {
	if t != nil {
		fu.SetUpdatedAt(*t)
	}
	return fu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (fu *FavouritesUpdate) ClearUpdatedAt() *FavouritesUpdate {
	fu.mutation.ClearUpdatedAt()
	return fu
}

// SetDeletedAt sets the "deleted_at" field.
func (fu *FavouritesUpdate) SetDeletedAt(t time.Time) *FavouritesUpdate {
	fu.mutation.SetDeletedAt(t)
	return fu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fu *FavouritesUpdate) SetNillableDeletedAt(t *time.Time) *FavouritesUpdate {
	if t != nil {
		fu.SetDeletedAt(*t)
	}
	return fu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fu *FavouritesUpdate) ClearDeletedAt() *FavouritesUpdate {
	fu.mutation.ClearDeletedAt()
	return fu
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (fu *FavouritesUpdate) SetProductID(id int) *FavouritesUpdate {
	fu.mutation.SetProductID(id)
	return fu
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (fu *FavouritesUpdate) SetNillableProductID(id *int) *FavouritesUpdate {
	if id != nil {
		fu = fu.SetProductID(*id)
	}
	return fu
}

// SetProduct sets the "product" edge to the Product entity.
func (fu *FavouritesUpdate) SetProduct(p *Product) *FavouritesUpdate {
	return fu.SetProductID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (fu *FavouritesUpdate) SetUserID(id int) *FavouritesUpdate {
	fu.mutation.SetUserID(id)
	return fu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (fu *FavouritesUpdate) SetNillableUserID(id *int) *FavouritesUpdate {
	if id != nil {
		fu = fu.SetUserID(*id)
	}
	return fu
}

// SetUser sets the "user" edge to the User entity.
func (fu *FavouritesUpdate) SetUser(u *User) *FavouritesUpdate {
	return fu.SetUserID(u.ID)
}

// Mutation returns the FavouritesMutation object of the builder.
func (fu *FavouritesUpdate) Mutation() *FavouritesMutation {
	return fu.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (fu *FavouritesUpdate) ClearProduct() *FavouritesUpdate {
	fu.mutation.ClearProduct()
	return fu
}

// ClearUser clears the "user" edge to the User entity.
func (fu *FavouritesUpdate) ClearUser() *FavouritesUpdate {
	fu.mutation.ClearUser()
	return fu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FavouritesUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fu.hooks) == 0 {
		affected, err = fu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FavouritesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fu.mutation = mutation
			affected, err = fu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fu.hooks) - 1; i >= 0; i-- {
			if fu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FavouritesUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FavouritesUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FavouritesUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FavouritesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   favourites.Table,
			Columns: favourites.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: favourites.FieldID,
			},
		},
	}
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldCreatedAt,
		})
	}
	if value, ok := fu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldUpdatedAt,
		})
	}
	if fu.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: favourites.FieldUpdatedAt,
		})
	}
	if value, ok := fu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldDeletedAt,
		})
	}
	if fu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: favourites.FieldDeletedAt,
		})
	}
	if fu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   favourites.ProductTable,
			Columns: []string{favourites.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   favourites.ProductTable,
			Columns: []string{favourites.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourites.UserTable,
			Columns: []string{favourites.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourites.UserTable,
			Columns: []string{favourites.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favourites.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// FavouritesUpdateOne is the builder for updating a single Favourites entity.
type FavouritesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavouritesMutation
}

// SetCreatedAt sets the "created_at" field.
func (fuo *FavouritesUpdateOne) SetCreatedAt(t time.Time) *FavouritesUpdateOne {
	fuo.mutation.SetCreatedAt(t)
	return fuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fuo *FavouritesUpdateOne) SetNillableCreatedAt(t *time.Time) *FavouritesUpdateOne {
	if t != nil {
		fuo.SetCreatedAt(*t)
	}
	return fuo
}

// SetUpdatedAt sets the "updated_at" field.
func (fuo *FavouritesUpdateOne) SetUpdatedAt(t time.Time) *FavouritesUpdateOne {
	fuo.mutation.SetUpdatedAt(t)
	return fuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fuo *FavouritesUpdateOne) SetNillableUpdatedAt(t *time.Time) *FavouritesUpdateOne {
	if t != nil {
		fuo.SetUpdatedAt(*t)
	}
	return fuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (fuo *FavouritesUpdateOne) ClearUpdatedAt() *FavouritesUpdateOne {
	fuo.mutation.ClearUpdatedAt()
	return fuo
}

// SetDeletedAt sets the "deleted_at" field.
func (fuo *FavouritesUpdateOne) SetDeletedAt(t time.Time) *FavouritesUpdateOne {
	fuo.mutation.SetDeletedAt(t)
	return fuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (fuo *FavouritesUpdateOne) SetNillableDeletedAt(t *time.Time) *FavouritesUpdateOne {
	if t != nil {
		fuo.SetDeletedAt(*t)
	}
	return fuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (fuo *FavouritesUpdateOne) ClearDeletedAt() *FavouritesUpdateOne {
	fuo.mutation.ClearDeletedAt()
	return fuo
}

// SetProductID sets the "product" edge to the Product entity by ID.
func (fuo *FavouritesUpdateOne) SetProductID(id int) *FavouritesUpdateOne {
	fuo.mutation.SetProductID(id)
	return fuo
}

// SetNillableProductID sets the "product" edge to the Product entity by ID if the given value is not nil.
func (fuo *FavouritesUpdateOne) SetNillableProductID(id *int) *FavouritesUpdateOne {
	if id != nil {
		fuo = fuo.SetProductID(*id)
	}
	return fuo
}

// SetProduct sets the "product" edge to the Product entity.
func (fuo *FavouritesUpdateOne) SetProduct(p *Product) *FavouritesUpdateOne {
	return fuo.SetProductID(p.ID)
}

// SetUserID sets the "user" edge to the User entity by ID.
func (fuo *FavouritesUpdateOne) SetUserID(id int) *FavouritesUpdateOne {
	fuo.mutation.SetUserID(id)
	return fuo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (fuo *FavouritesUpdateOne) SetNillableUserID(id *int) *FavouritesUpdateOne {
	if id != nil {
		fuo = fuo.SetUserID(*id)
	}
	return fuo
}

// SetUser sets the "user" edge to the User entity.
func (fuo *FavouritesUpdateOne) SetUser(u *User) *FavouritesUpdateOne {
	return fuo.SetUserID(u.ID)
}

// Mutation returns the FavouritesMutation object of the builder.
func (fuo *FavouritesUpdateOne) Mutation() *FavouritesMutation {
	return fuo.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (fuo *FavouritesUpdateOne) ClearProduct() *FavouritesUpdateOne {
	fuo.mutation.ClearProduct()
	return fuo
}

// ClearUser clears the "user" edge to the User entity.
func (fuo *FavouritesUpdateOne) ClearUser() *FavouritesUpdateOne {
	fuo.mutation.ClearUser()
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FavouritesUpdateOne) Select(field string, fields ...string) *FavouritesUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Favourites entity.
func (fuo *FavouritesUpdateOne) Save(ctx context.Context) (*Favourites, error) {
	var (
		err  error
		node *Favourites
	)
	if len(fuo.hooks) == 0 {
		node, err = fuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FavouritesMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fuo.mutation = mutation
			node, err = fuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fuo.hooks) - 1; i >= 0; i-- {
			if fuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, fuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Favourites)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from FavouritesMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FavouritesUpdateOne) SaveX(ctx context.Context) *Favourites {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FavouritesUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FavouritesUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FavouritesUpdateOne) sqlSave(ctx context.Context) (_node *Favourites, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   favourites.Table,
			Columns: favourites.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: favourites.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Favourites.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favourites.FieldID)
		for _, f := range fields {
			if !favourites.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favourites.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.CreatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldCreatedAt,
		})
	}
	if value, ok := fuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldUpdatedAt,
		})
	}
	if fuo.mutation.UpdatedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: favourites.FieldUpdatedAt,
		})
	}
	if value, ok := fuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: favourites.FieldDeletedAt,
		})
	}
	if fuo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: favourites.FieldDeletedAt,
		})
	}
	if fuo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   favourites.ProductTable,
			Columns: []string{favourites.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   favourites.ProductTable,
			Columns: []string{favourites.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourites.UserTable,
			Columns: []string{favourites.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favourites.UserTable,
			Columns: []string{favourites.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Favourites{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favourites.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
