// Code generated by ent, DO NOT EDIT.

package ent

import "context"

func (c *Category) Product(ctx context.Context) ([]*Product, error) {
	result, err := c.Edges.ProductOrErr()
	if IsNotLoaded(err) {
		result, err = c.QueryProduct().All(ctx)
	}
	return result, err
}

func (pr *Product) Category(ctx context.Context) (*Category, error) {
	result, err := pr.Edges.CategoryOrErr()
	if IsNotLoaded(err) {
		result, err = pr.QueryCategory().Only(ctx)
	}
	return result, MaskNotFound(err)
}
