-- create "categories" table
CREATE TABLE "categories"
(
    "id"         bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"       character varying NOT NULL,
    "created_at" timestamptz       NOT NULL,
    "updated_at" timestamptz       NULL,
    "deleted_at" timestamptz       NULL,
    "icon"       character varying NOT NULL,
    PRIMARY KEY ("id")
);
-- create index "categories_name_key" to table: "categories"
CREATE UNIQUE INDEX "categories_name_key" ON "categories" ("name");
-- create index "categories_icon_key" to table: "categories"
CREATE UNIQUE INDEX "categories_icon_key" ON "categories" ("icon");
-- create "users" table
CREATE TABLE "users"
(
    "id"            bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_name"     character varying NULL,
    "created_at"    timestamptz       NOT NULL,
    "updated_at"    timestamptz       NULL,
    "deleted_at"    timestamptz       NULL,
    "password_hash" character varying NOT NULL,
    "phone_number"  character varying NOT NULL,
    "is_verified"   boolean           NOT NULL DEFAULT false,
    "profile_image" character varying NOT NULL DEFAULT '',
    "email"         character varying NOT NULL,
    PRIMARY KEY ("id")
);
-- create index "users_password_hash_key" to table: "users"
CREATE UNIQUE INDEX "users_password_hash_key" ON "users" ("password_hash");
-- create index "users_phone_number_key" to table: "users"
CREATE UNIQUE INDEX "users_phone_number_key" ON "users" ("phone_number");
-- create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
-- create index "user_user_name_email" to table: "users"
CREATE UNIQUE INDEX "user_user_name_email" ON "users" ("user_name", "email");
-- create "products" table
CREATE TABLE "products"
(
    "id"               bigint            NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name"             character varying NOT NULL,
    "price"            character varying NOT NULL,
    "description"      character varying NOT NULL,
    "ingredients"      character varying NOT NULL,
    "total_rating"     double precision  NOT NULL DEFAULT 0,
    "images"           jsonb             NOT NULL,
    "created_at"       timestamptz       NOT NULL,
    "updated_at"       timestamptz       NULL,
    "deleted_at"       timestamptz       NULL,
    "category_product" bigint            NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "products_categories_product" FOREIGN KEY ("category_product") REFERENCES "categories" ("id") ON DELETE CASCADE
);
-- create index "products_name_key" to table: "products"
CREATE UNIQUE INDEX "products_name_key" ON "products" ("name");
